# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/checkout@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm cache clean --force
    - run: npm ci
    - run: npm run build --if-present
    - run: npm ci
    - name: build folder
      run: npm run build --if-present
      env:
         CI: false
         PAT_TOKEN: ${{ secrets.PAT}}
    - name: Deploy to GH Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.PAT }}
        publish_dir: ./build
